### PR TITLE
Trim leading spaces for copied lines

### PR DESCRIPTION
**Pull request by mattyoho**
Detect the number of leading spaces from the first line and trim that number from all lines.

This is a work in progress, written on my phone, not ready for prime time or tested.

### CODE REVIEW

**Comment by lynnwallenstein** [comment]
So tested this https://github.com/lynnwallenstein/lazydoc/tree/patch-1 ... while it doesn't break anything, it also doesn't seem to do anything :)

**Comment by mattyoho** [comment]
Haha, well, I was drinking. :smiley:. I'll take a look again.

**Comment by lynnwallenstein** [comment]
the fact that it didn't break and you did this on a phone and while drinking I think is amazing unto itself.

**Comment by lynnwallenstein** [comment]
LOL

**Comment by mattyoho** [comment]
Winter cleaning. :sweat_smile:

**Pull request closed without merging**
